pico-8/awesome-PICO-8

README.md
These scripts work very nicely!
=> pico2png perl scripts

README.md
Here's a collection of scripts that I've been using personally!
=> Adding pico8utils

README.md
The old cheat sheet was still for pico-8 v0.1.1.
Updated it to link to another one written for pico-8 v0.1.6 (latest).
=> changed cheat sheet reference to point to an updated one

README.md
Updated Slack Team link and added a new one that points to the original invite form running at JTE's server.
=> updated slack

README.md
- Added Sublime PICO-8 to the tools section.
- Fixed some missing full stops at the end of some descriptions (as `CONTRIBUTING.md` says).
=> added sublime-PICO-8

README.md
A printer friendly and reduced cheat sheet. 
I created it for a beginners programming workshop.
https://ztiromoritz.github.io/pico-8-spick/
=> Yet another cheat sheet

README.md
Self-plug of my 16 GIF screencapture of writing a game from scratch.
Someone might find it useful to code-along.
https://ztiromoritz.github.io/pico-8-shooter/
=> Tutorial - Spaceshoter in 16 GIFs

README.md
Added link to GitHub repo describing some tips&tricks related to the token optimization in Pico-8
=> token optimization

README.md
added the TIC-80 tiny computer
=> added a clone section + new entry

README.md
=> added text editors section + entry

README.md
Zep explains how to access the current audio being played.
http://www.lexaloffle.com/bbs/?pid=10719#p10719
=> added Tracker State/Audio Memory Locations to Hacks

README.md
Four undocumented memory locations that apply additional effects to SFX being played.
http://www.lexaloffle.com/bbs/?tid=3561
=> added SFX Modifications to Hacks

README.md
=> Add PX8 link

README.md
https://discord.gg/EwQ86eq
Fairly active chat started on the BBS [here](http://www.lexaloffle.com/bbs/index.php?pid=27037)
=> added Discord chat server

README.md
This cheat sheet was posted on the BBS as an enhancement to the PDF cheat sheet.
> This version fits best on a 1080p screen (or closer aspect ratio),
while the pdf version fits best on an A4/letter size paper.
--  https://www.lexaloffle.com/bbs/?tid=28207
=> Yet another yet another cheat sheet

README.md
https://github.com/outkine/pico-kit
This is a useful little library that I think could help a lot of beginners.
=> Add Pico-Kit to tools

README.md
Hello, similar to my last PR, #36 
This is another build tool I used for [Get Dis Money](https://getdismoney.com/).
Please let me know how it looks, thanks!
=> Added pico8Grunt Under Tools

README.md
Hello!
I just released my build tool for my game, [Get Dis Money](https://getdismoney.com/). And I wanted to add the build tool I made for it [picoDeploy](https://github.com/torch2424/picoDeploy).
Please let me know how it works, and thank you for making such an awesome, awesome list!
=> Added picoDeploy under Tools

README.md
Hey, this is a small library I've written for the PICO-8. I'd appreciate it being added to the list! Thanks.
https://github.com/JoebRogers/PICO-EC
=> Added PICO-EC

README.md
[p8](https://github.com/jozanza/p8) is a tool I wrote a couple years ago that I used for my own personal development flow. I really enjoyed coding dependency management and build tools in the JavaScript ecosystem. This was my attempt to bring a little bit of that magic to the PICO-8 world in hopes that it helps folks share code more easily, see their code run faster, and even use MoonScript if they really wanted do something crazy.
=> Added p8 to Tools section of README

README.md
I think this template should be used more, cause it fixes some major fullscreen issues, and looks great :)
=> Added custom html template

README.md
Besides, would you be willing to join the unofficial GitHub org: https://github.com/pico-8 :smile: , leave a comment if anyone want to join, I'll send you the invitation. :heart:
=>  Add GameShell hardware and use https links

README.md
Added a useful tool to help with the `fillp` function and its parameters.
=> Added fillp tool to 'tools' category

README.md
(And removing a trailing whitespace from the previous line.)
=> Adding picoCAD

README.md
Hey 👋 
I've just written [pico8-deploy](https://github.com/tducasse/pico8-deploy) a few days ago, so I thought I would add it to the the kist 😄
=> Add pico8-deploy

README.md
This is a project that allows you to build PICO-8 carts using TypeScript.
=> Add tspico8

README.md
I made it so that all of the headers are uniform and not all over the place
=> Make everything organized

README.md
A new aggressive minifier (plus some other tools, like a linter).
=> Added Shrinko8 to Tools

README.md
This pr also removes a link to a sprite editor which has a broken dropbox download link.
https://github.com/lesleyrs/pico-paint - https://www.lexaloffle.com/bbs/?tid=51270
Above is my tool to make sprites in a unique way that doesn't require a mouse, has the ability to copy to and paste from pico-8 games.
=> added my pixel art tool made in pico-8 for pico-8

README.md
see: https://github.com/Siapran/p8-canvas
=> Add p8-canvas.
